<?php declare(strict_types = 1);

/**
 * @file
 * Provides a museum entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function egam_museum_theme(): array {
  return [
    'museum' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for museum templates.
 *
 * Default template: museum.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the museum information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_museum(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function egam_museum_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish musea.
      $storage = \Drupal::entityTypeManager()->getStorage('museum');
      $museum_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($museum_ids) as $museum) {
        $museum->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize musea.
      $storage = \Drupal::entityTypeManager()->getStorage('museum');
      $museum_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($museum_ids) as $museum) {
        $museum->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function egam_museum_user_predelete(UserInterface $account): void {
  // Delete musea that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('museum');
  $museum_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($museum_ids)
  );
  // Delete old revisions.
  $museum_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($museum_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}

function egam_museum_theme_suggestions_museum_alter(array &$suggestions, array $vars, $hook) {
	$suggestions = [];
	if ($vars['elements']['#museum']) {
		if (isset($vars['elements']['#view_mode'])) {
			$suggestions[] = 'museum__' . $vars['elements']['#view_mode'];
		}
	}
}