<?php declare(strict_types = 1);

/**
 * @file
 * Provides a game entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\egam_global\Entities;
use Drupal\egam_global\Handler\RelatedContentHandler;
use Drupal\egam_global\Service\ContextManager;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function egam_game_theme(): array {
  return [
    'game' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for game templates.
 *
 * Default template: game.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the game information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_game(array &$variables): void {
  $variables['view_mode'] = $viewMode = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
	/* @var \Drupal\egam_game\Entity\Game $game */
	$game = $variables['elements']['#game'];
	if ($viewMode == 'teaser') {
		$variables['full_title'] = $game->getFullTitle();
		$variables['#cache']['contexts'][] = 'url';
	}
}

/**
 * Implements hook_page_attachments().
 */
function egam_screenshot_page_attachments(array &$attachments) {
	$attachments['#attached']['library'][] = 'egam/screenshot';
}

/**
 * Implements hook_user_cancel().
 */
function egam_game_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish games.
      $storage = \Drupal::entityTypeManager()->getStorage('game');
      $game_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck()
        ->execute();
      foreach ($storage->loadMultiple($game_ids) as $game) {
        $game->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize games.
      $storage = \Drupal::entityTypeManager()->getStorage('game');
      $game_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck()
        ->execute();
      foreach ($storage->loadMultiple($game_ids) as $game) {
        $game->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function egam_game_user_predelete(UserInterface $account): void {
  // Delete games that belong to this account.
	/** @var \Drupal\Core\Entity\ContentEntityStorageInterface $storage */
  $storage = \Drupal::entityTypeManager()->getStorage('game');
  $game_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck()
    ->execute();
  $storage->delete(
    $storage->loadMultiple($game_ids)
  );
  // Delete old revisions.
  $game_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck()
    ->execute();
  foreach (array_keys($game_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}


/**
 * Implements hook_preprocess().
 */
function egam_game_preprocess_game(&$variables) {
	if ($variables['view_mode'] == 'full') {
		/* @var \Drupal\egam_game\GameInterface $game */
		$game = $variables['elements']['#game'];
		$relatedContentHandler = RelatedContentHandler::me();
		$variables['related_artworks'] = $relatedContentHandler->viewContent($game, Entities::Screenshot);
		if (!empty($variables['related_artworks'])) {
			$variables['multiple_content'] = $relatedContentHandler->hasMultipleRelatedContent;
		}
	}
}