<?php

use Drupal\egam_global\Controller\HomeController;
use Drupal\egam_global\Entities;

/**
 * @file
 * Primary module hooks for EGAM Global module.
 */
function egam_global_theme($existing, $type, $theme, $path) {
	return [
		HomeController::TEMPLATE => [
			'variables' => [
				'cover_src' => NULL,
				'title' => NULL,
				'home_menu' => NULL,
			],
		],
	];
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function egam_global_theme_suggestions_alter(array &$suggestions, array &$variables, $hook) {
	if (isset($variables['elements']['#view_mode'])) {
		$suggestions[] = $hook . '__' . $variables['elements']['#view_mode'];
	}
	if ($hook == 'field') {
		$suggestions[] = $hook . '__' . $variables['element']['#bundle'] . '_' . $variables['element']['#field_name'] . '_' . $variables['element']['#view_mode'];
	}
}

/**
 * Implements hook_page_attachments().
 */
function egam_global_page_attachments(array &$attachments) {
	$attachments['#attached']['library'][] = 'egam/swiper';
	$attachments['#attached']['library'][] = 'egam/alpine-js';
}
